config/routes.rb
Rails.application.routes.draw do
  get 'colors/red', to: 'colors#red'
  get 'colors/blue', to: 'colors#blue'
  get 'colors/green', to: 'colors#green'
  root 'normals#home'
  get 'find', to: 'normals#find'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  def red
  end

  def blue
  end

  def green
  end
end

app/controllers/normals_controller.rb
class NormalsController < ApplicationController
  def home
  end

  def find
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/normals_helper.rb
module NormalsHelper
end

app/views/colors/blue.html.erb
<h1>Colors#blue</h1>
<p>Find me in app/views/colors/blue.html.erb</p>

app/views/colors/green.html.erb
<h1>Colors#green</h1>
<p>Find me in app/views/colors/green.html.erb</p>

app/views/colors/red.html.erb
<div class="red-wrapper">
  <div class="red-image">
    <p><%= image_tag('/color1.jpg') %></p>
    <span>Red</span>
    <div class="red-point"></div>
    <div id="red-image-under">
      <div class="red-upper-point">
        </div>
    </div>
  </div>

  <div class="red-sample-wrapper">
    <div class="red-sample-wrapper1">
      <div class="red-flex1">
        <div class="red-sample-1">
          <div class="red-sample-content1">
            <div class="red-sample1" onclick="redImage(1)">
              <%= image_tag('/google+.png') %>
            </div>
          </div>
          <p id="red-font-color1">Google Plus</p>
          <p id="red-font-p"><input type="text" value="#DD5144" id="sample--1" readonly></p>
        </div>

        <div class="red-sample-2">
          <div class="red-sample-content2">
            <div class="red-sample2" onclick="redImage(2)">
              <%= image_tag('/insta.png') %>
            </div>
          </div>
          <p id="red-font-color2">Instagram</p>
          <p id="red-font-p"><input type="text" value="#D93177" id="sample--2" readonly></p>
        </div>

        <div class="red-sample-3">
          <div class="red-sample-content3">
            <div class="red-sample3" onclick="redImage(3)">
              <%= image_tag('/pint.png') %>
            </div>
          </div>
          <p id="red-font-color3">Pinterest</p>
          <p id="red-font-p"><input type="text" value="#BD081C" id="sample--3" readonly></p>
        </div>
      </div>

      <div class="red-sample-7">
        <div class="red-sample-content7">
          <div class="red-sample7" onclick="redImage(7)">
            <%= image_tag('/ted.png') %>
          </div>
        </div>
        <p id="red-font-color7">TED</p>
        <p id="red-font-p"><input type="text" value="#DA281C" id="sample--7" readonly></p>
      </div>

      <div class="red-flex2">
        <div class="red-sample-4">
          <div class="red-sample-content4">
            <div class="red-sample4" onclick="redImage(4)">
              <%= image_tag('/mercari.png') %>
            </div>
          </div>
          <p id="red-font-color4">メルカリ</p>
          <p id="red-font-p"><input type="text" value="#E3463D" id="sample--4" readonly></p>
        </div>

        <div class="red-sample-5">
          <div class="red-sample-content5">
            <div class="red-sample5" onclick="redImage(5)">
              <%= image_tag('/money.png') %>
            </div>
          </div>
          <p id="red-font-color5">Money forward</p>
          <p id="red-font-p"><input type="text" value="#E27610" id="sample--5" readonly></p>
        </div>

        <div class="red-sample-6">
          <div class="red-sample-content6">
            <div class="red-sample6" onclick="redImage(6)">
              <%= image_tag('/flicker.png') %>
            </div>
          </div>
          <p id="red-font-color6">flicker</p>
          <p id="red-font-p"><input type="text" value="#E27610" id="sample--6" readonly></p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="sss" style="background: #DA281C; width: 400px; height: 400px">

</div>

<%= javascript_include_tag 'color1.js' %>

app/views/layouts/_footer.html.erb
<div class="footer-wrapper">
  <div class="footer-main">
    <div class="home-sns">
      <span id="home-g"><i class="fa fa-google"></i></span>
      <span id="home-f"><i class="fa fa-facebook"></i></span>
      <span id="home-t"><i class="fa fa-twitter"></i></span>
      <span id="home-i"><i class="fa fa-instagram"></i></span>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <div class="header-logo">
    <%= link_to root_path do %>
    <h1 class="logo">Iro Iro</h1>
    <% end %>
  </div>
  <ul id="helpnav">
    <%= link_to '#' do %>
    <li class="navLists helpNav-1" onmouseover="headerCursorOver(1)" onmouseout="headerCursorOut(1)">
      <p><i class="fa fa-paint-brush"></i></p>
      <span>色を探す</span>
      <ul class="hnl helpNavList-1">
        <h2>Find Color</h2>
        <%= link_to colors_red_path do %>
        <li><div class="hnl-red"></div>Red</li>
        <% end %>
        <%= link_to colors_blue_path do %>
        <li><div class="hnl-blue"></div>Blue</li>
        <% end %>
        <%= link_to colors_red_path do %>
        <li><div class="hnl-yellow"></div>Yellow</li>
        <% end %>
        <%= link_to colors_green_path do %>
        <li><div class="hnl-green"></div>Green</li>
        <% end %>
      </ul>
    </li>
    <% end %>
    <%= link_to find_path do %>
    <li class="navLists helpNav-2" onmouseover="headerCursorOver(2)" onmouseout="headerCursorOut(2)">
      <i class="fa fa-hourglass-half"></i>
      <span>色を配合する</span>
      <ul class="hnl helpNavList-2">
        <h2>Comibine Colors with</h2>
        <li><div class="hnl-red"></div>Red</li>
        <li><div class="hnl-blue"></div>Blue</li>
        <li><div class="hnl-yellow"></div>Yellow</li>
        <li><div class="hnl-green"></div>Green</li>
      </ul>
    </li>
    <% end %>
    <%= link_to '#' do %>
    <li class="navLists helpNav-3" onmouseover="headerCursorOver(3)" onmouseout="headerCursorOut(3)">
      <i class="fa fa-question-circle"></i>
      <span>お問い合わせ</span>
    </li>
    <% end %>
    <%= link_to '#' do %>
    <li class="navLists helpNav-4" onmouseover="headerCursorOver(4)" onmouseout="headerCursorOut(4)">
      <i class="fa fa-sticky-note-o"></i>
      <span>サイト情報</span>
    </li>
    <% end %>
    <%= link_to '#' do %>
    <li class="navLists helpNav-5" onmouseover="headerCursorOver(5)" onmouseout="headerCursorOut(5)">
      <i class="fa fa-map-pin"></i>
      <span>アクセス</span>
    </li>
    <% end %>
  </ul>
</div>
<%= javascript_include_tag 'header.js' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Iro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="assets/css/fakeLoader.css">
    <script src="assets/fakeloader/fakeLoader.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <div id='fakeloader'  class="fakeloader"></div>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <%= javascript_include_tag 'main.js' %>
    <%= javascript_include_tag 'fakeLoader.js' %>
  </body>
</html>

app/views/normals/_blue.html.erb
<div class="home-blue">
  <p>Blue to Black</p>
  <div class="home-red-select">
    <div class="home-red-select-info">
      <div id="blue-1" class="blue-scr" value="#00FF00" onclick="copyColorBlue(1)" onmouseover="blueSelectAdd(1)" onmouseout="blueSelectRemove(1)"></div>
      <input type="text" name="" value="#00FF00" id="blue--1" readonly>
      <span>R:255</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-2" class="blue-scr" value="#ee0000" onclick="copyColorBlue(2)" onmouseover="blueSelectAdd(2)" onmouseout="blueSelectRemove(2)"></div>
      <input type="text" name="" value="#ee0000" id="blue--2" readonly>
      <span>R:238</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-3" class="blue-scr" value="#dd0000" onclick="copyColorBlue(3)" onmouseover="blueSelectAdd(3)" onmouseout="blueSelectRemove(3)"></div>
      <input type="text" name="" value="#dd0000" id="blue--3" readonly>
      <span>R:221</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-4" class="blue-scr" value="#cc0000" onclick="copyColorBlue(4)" onmouseover="blueSelectAdd(4)" onmouseout="blueSelectRemove(4)"></div>
      <input type="text" name="" value="#cc0000" id="blue--4" readonly>
      <span>R:204</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-5" class="blue-scr" value="#bb0000" onclick="copyColorBlue(5)" onmouseover="blueSelectAdd(5)" onmouseout="blueSelectRemove(5)"></div>
      <input type="text" name="" value="#bb0000" id="blue--5" readonly>
      <span>R:187</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-6" class="blue-scr" value="#aa0000" onclick="copyColorBlue(6)" onmouseover="blueSelectAdd(6)" onmouseout="blueSelectRemove(6)"></div>
      <input type="text" name="" value="#aa0000" id="blue--6" readonly>
      <span>R:170</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-7" class="blue-scr" value="#990000" onclick="copyColorBlue(7)" onmouseover="blueSelectAdd(7)" onmouseout="blueSelectRemove(7)"></div>
      <input type="text" name="" value="#990000" id="blue--7" readonly>
      <span>R:153</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-8" class="blue-scr" value="#880000" onclick="copyColorBlue(8)" onmouseover="blueSelectAdd(8)" onmouseout="blueSelectRemove(8)"></div>
      <input type="text" name="" value="#880000" id="blue--8" readonly>
      <span>R:136</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-9" class="blue-scr" value="#770000" onclick="copyColorBlue(9)" onmouseover="blueSelectAdd(9)" onmouseout="blueSelectRemove(9)"></div>
      <input type="text" name="" value="#770000" id="blue--9" readonly>
      <span>R:119</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-10" class="blue-scr" value="#660000" onclick="copyColorBlue(10)" onmouseover="blueSelectAdd(10)" onmouseout="blueSelectRemove(10)"></div>
      <input type="text" name="" value="#660000" id="blue--10" readonly>
      <span>R:102</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-11" class="blue-scr" value="#550000" onclick="copyColorBlue(11)" onmouseover="blueSelectAdd(11)" onmouseout="blueSelectRemove(11)"></div>
      <input type="text" name="" value="#550000" id="blue--11" readonly>
      <span>R:85</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-12" class="blue-scr" value="#440000" onclick="copyColorBlue(12)" onmouseover="blueSelectAdd(12)" onmouseout="blueSelectRemove(12)"></div>
      <input type="text" name="" value="#440000" id="blue--12" readonly>
      <span>R:68</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-13" class="blue-scr" value="#330000" onclick="copyColorBlue(13)" onmouseover="blueSelectAdd(13)" onmouseout="blueSelectRemove(13)"></div>
      <input type="text" name="" value="#330000" id="blue--13" readonly>
      <span>R:51</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-14" class="blue-scr" value="#220000" onclick="copyColorBlue(14)" onmouseover="blueSelectAdd(14)" onmouseout="blueSelectRemove(14)"></div>
      <input type="text" name="" value="#220000" id="blue--14" readonly>
      <span>R:34</br>G:0</br>B:0</span>
    </div>
  </div>
  <p>Several Blue</p>
  <div class="home-red-select">
    <div class="home-red-select-info">
      <div id="blue-15" class="blue-scr" value="#32cd32" onclick="copyColorBlue(15)" onmouseover="blueSelectAdd(15)" onmouseout="blueSelectRemove(15)"></div>
      <input type="text" name="" value="#32cd32" id="blue--15" readonly>
      <span>R:255</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-16" class="blue-scr" value="#ff1111" onclick="copyColorBlue(16)" onmouseover="blueSelectAdd(16)" onmouseout="blueSelectRemove(16)"></div>
      <input type="text" name="" value="#ff1111" id="blue--16" readonly>
      <span>R:255</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-17" class="blue-scr" value="#ff2222" onclick="copyColorBlue(17)" onmouseover="blueSelectAdd(17)" onmouseout="blueSelectRemove(17)"></div>
      <input type="text" name="" value="#ff2222" id="blue--17" readonly>
      <span>R:255</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-18" class="blue-scr" value="#ff3333" onclick="copyColorBlue(18)" onmouseover="blueSelectAdd(18)" onmouseout="blueSelectRemove(18)"></div>
      <input type="text" name="" value="#ff3333" id="blue--18" readonly>
      <span>R:255</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-19" class="blue-scr" value="#ff4444" onclick="copyColorBlue(19)" onmouseover="blueSelectAdd(19)" onmouseout="blueSelectRemove(19)"></div>
      <input type="text" name="" value="#ff4444" id="blue--19" readonly>
      <span>R:255</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-20" class="blue-scr" value="#ff5555" onclick="copyColorBlue(20)" onmouseover="blueSelectAdd(20)" onmouseout="blueSelectRemove(20)"></div>
      <input type="text" name="" value="#ff5555" id="blue--20" readonly>
      <span>R:255</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-21" class="blue-scr" value="#ff6666" onclick="copyColorBlue(21)" onmouseover="blueSelectAdd(21)" onmouseout="blueSelectRemove(21)"></div>
      <input type="text" name="" value="#ff6666" id="blue--21" readonly>
      <span>R:255</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-22" class="blue-scr" value="#ff7777" onclick="copyColorBlue(22)" onmouseover="blueSelectAdd(22)" onmouseout="blueSelectRemove(22)"></div>
      <input type="text" name="" value="#ff7777" id="blue--22" readonly>
      <span>R:255</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-23" class="blue-scr" value="#ff8888" onclick="copyColorBlue(23)" onmouseover="blueSelectAdd(23)" onmouseout="blueSelectRemove(23)"></div>
      <input type="text" name="" value="#ff8888" id="blue--23" readonly>
      <span>R:255</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-24" class="blue-scr" value="#ff9999" onclick="copyColorBlue(24)" onmouseover="blueSelectAdd(24)" onmouseout="blueSelectRemove(24)"></div>
      <input type="text" name="" value="#ff9999" id="blue--24" readonly>
      <span>R:255</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-25" class="blue-scr" value="#ffaaaa" onclick="copyColorBlue(25)" onmouseover="blueSelectAdd(25)" onmouseout="blueSelectRemove(25)"></div>
      <input type="text" name="" value="#ffaaaa" id="blue--25" readonly>
      <span>R:255</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-26" class="blue-scr" value="#ffbbbb" onclick="copyColorBlue(26)" onmouseover="blueSelectAdd(26)" onmouseout="blueSelectRemove(26)"></div>
      <input type="text" name="" value="#ffbbbb" id="blue--26" readonly>
      <span>R:255</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <i><div id="blue-27" class="blue-scr" value="#ffcccc" onclick="copyColorBlue(27)" onmouseover="blueSelectAdd(27)" onmouseout="blueSelectRemove(27)"></div></i>
      <input type="text" name="" value="#ffcccc" id="blue--27" readonly>
      <span>R:255</br>G:0</br>B:0</span>
    </div>
    <div class="home-red-select-info">
      <div id="blue-28" class="blue-scr" value="#ffdddd" onclick="copyColorBlue(28)" onmouseover="blueSelectAdd(28)" onmouseout="blueSelectRemove(28)"></div>
      <input type="text" name="" value="#ffdddd" id="blue--28" readonly>
      <span>R:255</br>G:0</br>B:0</span>
    </div>
  </div>
</div>

app/views/normals/find.html.erb
<h1>hey</h1>
<p>changed this line for pullrequest</p>

app/views/normals/home.html.erb
<div class="home-wrapper">
  <div class="home-title">
    <h1>Iro Iro</h1>
    <p>色をクリックしますと、その色のコードをコピー出来ます（16進数）</p>
  </div>
  <div class="home-main">
    <%= render 'red' %>
    <%= render 'green' %>
    <%= render 'blue' %>
  </div>
</div>


<script src="https://cdn.jsdelivr.net/scrollreveal.js/3.0.3/scrollreveal.min.js"></script>

<script>
window.sr = ScrollReveal();
sr.reveal('.blue-scr', { easing: 'ease', origin: 'left', duration: 2000, distance: '400px', opacity: 0.8, scale: 1 });
</script>
<%= javascript_include_tag 'home.js' %>
<%= javascript_include_tag 'header.js' %>